application: tf2bay
version: 3
runtime: python
api_version: 1


handlers:

- url: /media/ttf/(.*\.ttf)
  static_files: media/ttf/\1
  expiration: "1d 1h"
  mime_type: font/ttf
  upload: media/ttf/(.*\.ttf)


- url: /media/(.*\.(css|js|png))
  static_files: media/\1
  expiration: "1d 1h"
  upload: media/(.*\.(css|js|png))


# lol
- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico


# private profile view: displays profile of current user
# private add listing view:  displays form for creating new listing
- url: /(profile|/listings/add)
  login: required
  script: main.py


# worker url for expiration task queue
- url: /api/v1/expire-listing
  login: admin
  script: main.py

# for testing
- url: /echo
  login: admin
  script: main.py


# private apis for listing and bid create, update and delete
- url: /api/v1/(add-listing|cancel-listing|add-bid|own-profile)
  script: main.py
  login: required


# public apis for a players listings and bids
- url: /api/v1/(listings|bids)/(\d{17})
  script: main.py


# public api for listing and bid reads
- url: /api/v1/(browse-listings|search-listings)
  script: main.py


# public pages
- url: (/|/login|/listings|/listings/search|/(.*))
  script: main.py
