api_version: 1
application: tf2bay
builtins:
-   datastore_admin: true
-   appstats: true
handlers:
-   expiration: 1d 1h
    mime_type: font/ttf
    static_files: media/ttf/\1
    upload: media/ttf/(.*\.(ttf|eot))
    url: /media/ttf/(.*\.(ttf|eot))
-   expiration: 1d 1h
    static_files: media/\1
    upload: media/(.*\.(css|js|png|gif))
    url: /media/(.*\.(css|js|png|gif))
-   static_files: media/img/favicon.ico
    upload: media/img/favicon.ico
    url: /favicon.ico
-   static_files: media/robots.txt
    upload: media/robots.txt
    url: /robots.txt
-   login: admin
    script: tf2bay/api/admin/\1/\2.py
    url: /api/v1/admin/(.*?)/(.*)
-   auth_fail_action: unauthorized
    login: required
    script: tf2bay/api/auth/\1.py
    url: /api/v1/auth/(.*?)/\d{17}
-   auth_fail_action: unauthorized
    login: required
    script: tf2bay/api/auth/\1.py
    url: /api/v1/auth/(.*)
-   script: tf2bay/api/public/\1.py
    url: /api/v1/public/(.*)/\d+
-   script: tf2bay/api/public/\1.py
    url: /api/v1/public/(.*)
-   login: admin
    script: tf2bay/scripts/admin/\1.py
    url: /(echo)
-   login: admin
    script: tf2bay/scripts/admin/shell.py
    url: /shell.*
-   auth_fail_action: unauthorized
    login: required
    script: tf2bay/scripts/auth/\1/\2.py
    url: /(listing)/(add)
-   auth_fail_action: unauthorized
    login: required
    script: tf2bay/scripts/auth/\1.py
    url: /(profile-update)(/.*)?
-   script: tf2bay/scripts/public/\1.py
    url: /(listing|profile)/\d{1,20}

-   script: tf2bay/scripts/public/\1.py
    url: /(search|login|terms|all-items|about|contact|faq)

-   script: tf2bay/scripts/public/front.py
    url: /
-   script: tf2bay/scripts/public/404.py
    url: .*
runtime: python
version: 22
