application: tf2bay
version: 3
runtime: python
api_version: 1


handlers:

- url: /media/(.*\.(css|js|png|ttf))
  static_files: media/\1
  expiration: "1d 1h"
  upload: media/(.*\.(css|js|png|ttf))

- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /(auction|profile)
  login: required
  script: main.py

- url: /echo
  login: admin
  script: main.py

- url: /api/v1/(add-listing|cancel-listing|add-bid)
  script: main.py
  login: required

- url: /api/v1/(get-listings|search-listings)
  script: main.py

- url: /(login|browse|search)
  script: main.py

- url: /
  script: main.py

- url: /(.*)
  script: main.py
