application: tf2bay
version: 3
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on


handlers:

  ## == Static Files == ##

- url: /media/ttf/(.*\.(ttf|eot))
  static_files: media/ttf/\1
  expiration: "1d 1h"
  mime_type: font/ttf
  upload: media/ttf/(.*\.(ttf|eot))

- url: /media/(.*\.(css|js|png|gif))
  static_files: media/\1
  expiration: "1d 1h"
  upload: media/(.*\.(css|js|png|gif))

- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico


  ## == API Methods == ##

- url: /api/v1/admin/(.*?)/(.*)
  login: admin
  script: tf2bay/api/admin/\1/\2.py

- url: /api/v1/auth/(.*?)/\d{17}
  login: required
  script: tf2bay/api/auth/\1.py
  auth_fail_action: unauthorized

- url: /api/v1/auth/(.*)
  login: required
  script: tf2bay/api/auth/\1.py
  auth_fail_action: unauthorized

- url: /api/v1/public/(.*)/\d+
  script: tf2bay/api/public/\1.py

- url: /api/v1/public/(.*)
  script: tf2bay/api/public/\1.py


  ## == User Interface == ##

- url: /(echo)
  login: admin
  script: tf2bay/scripts/admin/\1.py

- url: /shell.*
  login: admin
  script: tf2bay/scripts/admin/shell.py

- url: /(listing)/(add)
  login: required
  script: tf2bay/scripts/auth/\1/\2.py
  auth_fail_action: unauthorized

- url: /(profile-update)(/.*)
  login: required
  script: tf2bay/scripts/auth/\1.py
  auth_fail_action: unauthorized

- url: /(listing|profile)/\d{1,20}
  script: tf2bay/scripts/public/\1.py

- url: /(search|login|terms)
  script: tf2bay/scripts/public/\1.py

- url: /
  script: tf2bay/scripts/public/front.py

- url: .*
  script: tf2bay/scripts/public/404.py
