api_version: 1
application: tf2auctions
builtins:
-   datastore_admin: true
-   appstats: true
handlers:
-   script: tf2auctions/api/admin/remote.py
    url: /remote_api
-   expiration: 1d 1h
    mime_type: font/ttf
    static_files: media/ttf/\1
    upload: media/ttf/(.*\.(ttf|eot))
    url: /media/ttf/(.*\.(ttf|eot))
-   expiration: 1d 1h
    static_files: media/\1
    upload: media/(.*\.(css|js|png|gif|ico|jpg))
    url: /media/(.*\.(css|js|png|gif|ico|jpg))
-   static_files: media/img/favicon.ico
    upload: media/img/favicon.ico
    url: /favicon.ico
-   static_files: media/robots.txt
    upload: media/robots.txt
    url: /robots.txt
-   static_files: media/sitemap.gz
    upload: media/sitemap.gz
    url: /sitemap.gz
-   login: admin
    script: tf2auctions/api/admin/\1/\2.py
    url: /api/v1/admin/(.*?)/(.*)
-   auth_fail_action: unauthorized
    login: required
    script: tf2auctions/api/auth/\1.py
    url: /api/v1/auth/(.*?)/\d{17}
-   auth_fail_action: unauthorized
    login: required
    script: tf2auctions/api/auth/\1.py
    url: /api/v1/auth/(.*)
-   script: tf2auctions/api/public/\1.py
    url: /api/v1/public/(.*)/\d+
-   script: tf2auctions/api/public/profile.py
    url: /api/v1/public/profile/(.*)
-   script: tf2auctions/api/public/\1.py
    url: /api/v1/public/(.*)
-   login: admin
    script: tf2auctions/scripts/admin/\1.py
    url: /(echo)
-   login: admin
    script: tf2auctions/scripts/admin/shell.py
    url: /shell.*
-   auth_fail_action: unauthorized
    login: required
    script: tf2auctions/scripts/auth/\1/\2.py
    url: /(listing)/(add)
-   auth_fail_action: unauthorized
    login: required
    script: tf2auctions/scripts/auth/\1.py
    url: /(profile-update)(/.*)?
-   script: tf2auctions/scripts/public/search-redirect.py
    url: /(listing|profile)(/?)
-   script: tf2auctions/scripts/public/\1.py
    url: /(listing|profile)/\d{1,20}
-   script: tf2auctions/scripts/public/profile.py
    url: /id/(.{1,32})
-   script: tf2auctions/scripts/public/subscribe/index.py
    url: /subscribe
-   script: tf2auctions/scripts/public/subscribe/\1.py
    url: /subscribe/(cancel|thanks)
-   script: tf2auctions/scripts/public/\1.py
    url: /(search|login|terms|terms-dialog|all-items|all-attributes|about|backpack|support|openmarket|openmarket-dialog)
-   script: tf2auctions/scripts/public/front_rss.py
    url: /index.rss
-   script: tf2auctions/scripts/public/front.py
    url: /
-   script: tf2auctions/scripts/public/404.py
    url: .*
runtime: python
version: 93
