application: tf2bay
version: 1
runtime: python
api_version: 1


handlers:

- url: /media/(.*\.(css|js|png|ttf))
  static_files: media/\1
  expiration: "1d 1h"
  upload: media/(.*\.(css|js|png|ttf))

- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /(auction|profile)
  login: required
  script: main.py

- url: /(login|echo|browse|search)
  script: main.py

- url: /
  script: main.py

- url: /(.*)
  script: main.py
