#!/usr/bin/env python2.5
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.appengine.tools.os_compat
import os
import sys

from google.appengine.ext.remote_api import remote_api_stub
from IPython.Shell import start as ipython_start


os.environ['SERVER_SOFTWARE'] = 'Development (remote_api_shell)/1.0'
banner = 'App Engine Remote API Shell\nPython %s' % sys.version


def local_auth():
    return open('admin_key.nodist').readlines()[0].strip(), ''


def local_ns():
    from google.appengine.api import datastore
    from google.appengine.api import memcache
    from google.appengine.api import urlfetch
    from google.appengine.api import users
    from google.appengine.ext import db
    from google.appengine.ext import search
    import tf2auctions.lib, tf2auctions.models
    return locals()


def connect_remote_api(appid='tf2auctions', path='/remote_api'):
    remote_api_stub.ConfigureRemoteApi(
	appid,
	path,
	local_auth,
        servername=None,
        save_cookies=True,
	secure=False)
    remote_api_stub.MaybeInvokeAuthentication()


if __name__ == '__main__':
    connect_remote_api()
    ipython_start(user_ns=local_ns()).mainloop(banner=banner)
